name: Deploy on Strapi Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [strapi-content-updated]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy in DigitalOcean
        run: |
          curl -X POST "https://api.digitalocean.com/v2/apps/09e996b8-62fc-4581-81ca-952507195263/deployments/deployments" \
            -H "Authorization: Bearer dop_v1_5250ffc4a53abb67b39617cc3a0193cf25990e7a1082411b2c3d2bd620f191e3" \
            -H "Content-Type: application/json"
